[2024-11-28T12:05:44.578-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T12:05:44.581-0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_data_pipeline.extract_youtube_data scheduled__2024-11-27T00:00:00+00:00 [queued]>
[2024-11-28T12:05:44.583-0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_data_pipeline.extract_youtube_data scheduled__2024-11-27T00:00:00+00:00 [queued]>
[2024-11-28T12:05:44.583-0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-28T12:05:44.586-0600] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_youtube_data> on 2024-11-27 00:00:00+00:00
[2024-11-28T12:05:44.588-0600] {standard_task_runner.py:72} INFO - Started process 36605 to run task
[2024-11-28T12:05:44.591-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_data_pipeline', 'extract_youtube_data', 'scheduled__2024-11-27T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/youtube_data_pipeline.py', '--cfg-path', '/var/folders/zs/sf3lbkjd0p58grc25nrggk1h0000gn/T/tmpz8bh_7hy']
[2024-11-28T12:05:44.592-0600] {standard_task_runner.py:105} INFO - Job 7: Subtask extract_youtube_data
[2024-11-28T12:05:44.640-0600] {task_command.py:467} INFO - Running <TaskInstance: youtube_data_pipeline.extract_youtube_data scheduled__2024-11-27T00:00:00+00:00 [running]> on host mac.attlocal.net
[2024-11-28T12:05:44.657-0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='youtube_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_youtube_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T00:00:00+00:00'
[2024-11-28T12:05:44.657-0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-28T12:05:44.657-0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-28T12:05:44.657-0600] {logging_mixin.py:190} INFO - Current task name:extract_youtube_data state:running start_date:2024-11-28 18:05:44.582042+00:00
[2024-11-28T12:05:44.657-0600] {logging_mixin.py:190} INFO - Dag name:youtube_data_pipeline and current dag run status:running
[2024-11-28T12:05:44.658-0600] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T12:05:44.659-0600] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-11-28T12:05:44.778-0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/beprathap/airflow/dags/include/airflowYoutube.py", line 19, in airflowYoutube
    api.save_raw_json(channel_stats, raw_filename)
  File "/Users/beprathap/airflow/dags/include/youtube_api.py", line 96, in save_raw_json
    with open(filename, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/beprathap/airflow/dags/data/raw/channel_stats_20241128_120544.json'
[2024-11-28T12:05:44.785-0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-28T12:05:44.785-0600] {logging_mixin.py:190} INFO - Task start:2024-11-28 18:05:44.582042+00:00 end:2024-11-28 18:05:44.785224+00:00 duration:0.203182
[2024-11-28T12:05:44.786-0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_youtube_data> dag:<DAG: youtube_data_pipeline> dagrun:<DagRun youtube_data_pipeline @ 2024-11-27 00:00:00+00:00: scheduled__2024-11-27T00:00:00+00:00, state:running, queued_at: 2024-11-28 18:05:43.717333+00:00. externally triggered: False>
[2024-11-28T12:05:44.786-0600] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/Users/beprathap/airflow/dags/data/raw/channel_stats_20241128_120544.json'
[2024-11-28T12:05:44.787-0600] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_data_pipeline, task_id=extract_youtube_data, run_id=scheduled__2024-11-27T00:00:00+00:00, execution_date=20241127T000000, start_date=20241128T180544, end_date=20241128T180544
[2024-11-28T12:05:44.792-0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T12:05:44.792-0600] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task extract_youtube_data ([Errno 2] No such file or directory: '/Users/beprathap/airflow/dags/data/raw/channel_stats_20241128_120544.json'; 36605)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/beprathap/airflow/dags/include/airflowYoutube.py", line 19, in airflowYoutube
    api.save_raw_json(channel_stats, raw_filename)
  File "/Users/beprathap/airflow/dags/include/youtube_api.py", line 96, in save_raw_json
    with open(filename, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/beprathap/airflow/dags/data/raw/channel_stats_20241128_120544.json'
[2024-11-28T12:05:44.808-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T12:05:44.851-0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T12:05:44.851-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
